name: "Auto update üåè"
on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "v*"

jobs:
  auto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update locales
        uses: curse-action/locale@master
        with:
          token: ${{ secrets.CURSE_TOKEN }}

      - name: Update libs
        uses: curse-action/update@master
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSE_FORGE_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update locale/libs files"
