name: Auto update libs ðŸ§€
on:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"
    paths:
      - Libs/Libs.xml
      - .github/workflows/auto-update-libs.yml

jobs:
  auto-update-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update libs
        uses: curse-action/update@master
        with:
          curse-forge-token: ${{ secrets.CURSE_FORGE_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update locale/libs files"
